# Generated by Django 3.2.20 on 2023-08-29 11:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CustomOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customjewellerydesign',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='street_address1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customjewellerydesign',
            name='town_or_city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
