# Generated by Django 3.0.1 on 2023-10-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jewelleries', '0004_auto_20231023_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelleries.Jewellery')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whishlist.WishList')),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='jewelleries',
            field=models.ManyToManyField(related_name='product_wishlists', through='whishlist.WishListItem', to='jewelleries.Jewellery'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
