# Generated by Django 3.2.20 on 2023-07-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleries', '0002_auto_20230717_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewellery',
            options={'verbose_name_plural': 'Jewelleries'},
        ),
    ]
