# Generated by Django 3.2.20 on 2023-08-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleries', '0003_alter_jewellery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewellery',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Feature on Home Page'),
        ),
    ]
