# Generated by Django 3.0.1 on 2023-10-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleries', '0004_auto_20231023_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellery',
            name='diamond_carats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='diamond_shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jewellery',
            name='gold_karats',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
